### ISSUE TITLE
Could not load file or assembly 'Microsoft.ApplicationInsights'

### ISSUE THREAD

**Issue by MartinWickman** [Azure/azure-functions-openapi-extension#118]
Adding app insights dependency and a TelemetryInitializer to the app breaks with an error

### Steps to reproduce:

1. Follow the [tutorial ](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/enable-open-api-endpoints.md) 

2. Add Application insight packages:

```
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.17.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="0.7.2-preview" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" /> 
```

3. Add a Startup.cs with a `ITelemetryInitializer`

```
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using MyOpenApiFunctionApp;

[assembly: FunctionsStartup(typeof(Startup))]

namespace MyOpenApiFunctionApp
{
    using Microsoft.ApplicationInsights.Channel;
    using Microsoft.ApplicationInsights.Extensibility;
    using Microsoft.Azure.Functions.Extensions.DependencyInjection;
    using Microsoft.Extensions.DependencyInjection;

    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddSingleton<ITelemetryInitializer, TelemetryInitializer>();
        }
    }
    
    public class TelemetryInitializer : ITelemetryInitializer
    {
        public void Initialize(ITelemetry item) { }
    }
}
```

4. Start it
5. Go to http://localhost:7071/api/Swagger/ui
6. This error is displayed:

```
Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.17.0.146, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Resolvers.OpenApiConfigurationResolver.Resolve(Assembly assembly)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.get_OpenApiConfigurationOptions()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerUI(HttpRequest req, ExecutionContext ctx, ILogger log)
```

**Comment by justinyoo** [comment]
@MartinWickman Thanks for the issue! Let me have a look.

**Comment by GaryFreeman** [comment]
I've faced the same issue. It seems that some of the types in FunctionApp dll cannot be loaded because they depend on types in different assemblies which are not loaded.

I've created a minimal reproduction repository to help maintainers reproduce it.

https://github.com/GaryFreeman/AssemblyLoadMinimalReproductionFunctionApp

**Comment by GaryFreeman** [comment]
I've made a fix of that issue. Can you have a look, please?

https://github.com/Azure/azure-functions-openapi-extension/pull/152
