### ISSUE TITLE
Using examples gives a TypeLoadException

### ISSUE THREAD

**Issue by PehrGit** [Azure/azure-functions-openapi-extension#123]
When I add a Request Example, I get the following error when going to /swagger/ui or /swagger.json:

```
Unable to load one or more of the requested types.
Method 'Build' in type 'MyFunction.GroupRequestExample' from assembly 'MyFunction, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

      at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Resolvers.OpenApiConfigurationResolver.Resolve(Assembly assembly)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.get_OpenApiConfigurationOptions()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerDocument(HttpRequest req, String extension, ExecutionContext ctx, ILogger log)
```

Example class:
```
    public class GroupRequestExample: OpenApiExample<GroupRequest>
    {
        public override IOpenApiExample<GroupRequest> Build(NamingStrategy namingStrategy = null)
        {
            this.Examples.Add(OpenApiExampleResolver.Resolve("example", new GroupRequest()
            {
                Name = "ExampleGroup"
            }, namingStrategy));

            return this;
        }
    }
```

I don't even have to reference the example anywhere, just having it in the project leads to this error, no matter if I reference it in an attribute on the request class and/or the function

**Comment by justinyoo** [comment]
@PehrGit Thanks for the issue! Would you please let me know the repro?

**Comment by PehrGit** [comment]
@justinyoo that's the thing, if I do the exact same thing in a new project it works fine. So something in the actual project must be causing this but I can't figure out what. Any ideas where I might look to find the cause?

**Comment by justinyoo** [comment]
Interesting. Can you run these repos on your local machine?

* https://github.com/Azure/azure-functions-openapi-extension/tree/main/samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static
* https://github.com/aliencube/gymlog

The first one is the sample application in this repo and the second one is the one I use for my toy project. If both are working as expected, can you compare them to what you've just created?

**Comment by PehrGit** [comment]
@justinyoo I tried out both repos and they both worked fine. So I started removing all of the code and all of the references from our project to determine what was causing the error. I finally determined a PackageReference to Newtonsoft.Json to be the culprit. I've created a repro repo: https://github.com/PehrGit/AzureFunctionsFileLoadExceptionRepro

It contains two projects which both generate an error but each a slightly different one. When the reference to "Microsoft.NET.Sdk.Functions" is set to 3.0.3 we see this error:
```
Unable to load one or more of the requested types.
Method 'Build' in type 'FileLoadExceptionRepro.DummyStringModelExample' from assembly 'FileLoadExceptionReproNoImplementation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'Build' in type 'FileLoadExceptionRepro.DummyListModelExample' from assembly 'FileLoadExceptionReproNoImplementation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Resolvers.OpenApiConfigurationResolver.Resolve(Assembly assembly)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.get_OpenApiConfigurationOptions()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerDocument(HttpRequest req, String extension, ExecutionContext ctx, ILogger log)
```
 And when it is set to 3.0.11 we get this error:
```
Unable to load one or more of the requested types.
Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Resolvers.OpenApiConfigurationResolver.Resolve(Assembly assembly)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.get_OpenApiConfigurationOptions()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerUI(HttpRequest req, ExecutionContext ctx, ILogger log)
```

Any ideas? For now we are investigating if we even need that specific Newtonsoft.Json reference, if not then it's a simple fix on our end 🤞

**Comment by justinyoo** [comment]
Oh, the very Newtonsoft.Json one? 😱

**Comment by foconnor-DS** [comment]
Is there a workaround for this? I just tried to enable OpenAPIExamples for my API services and ran into this. I can't find a version 13.0.0.0 nuget for Newtonsoft, but maybe that's not the Nuget version. I tried installing 13.0.1 directly, to avoid this problem, but nogo. Can we do a binding redirect in the .csproj?

**Comment by foconnor-DS** [comment]
There's something funky going on here. If I add 
`<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>`
to my csproj, then the error goes away, and I get this error instead:

```
Unable to load one or more of the requested types.
Method 'Build' in type 'SampleQueryExample' from assembly 'Test.NT.Serverless, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Resolvers.OpenApiConfigurationResolver.Resolve(Assembly assembly)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.get_OpenApiConfigurationOptions()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerUI(HttpRequest req, ExecutionContext ctx, ILogger log)

```

The 'SampleQueryExample' is:

```
        public class SampleQueryExample : OpenApiExample<GetVideosWithPaginationQuery>
        {
            public override IOpenApiExample<GetVideosWithPaginationQuery> Build(NamingStrategy namingStrategy = null)
            {
                this.Examples.Add(
                    OpenApiExampleResolver.Resolve(
                        "sample1",
                        new GetVideosWithPaginationQuery() { RootDomain= "test", Subdomain="test" },
                        namingStrategy
                    ));

                return this;
            }
        }
        
```

**Comment by PehrGit** [comment]
In the end we just removed the `Newtonsoft.Json` reference, apparently it was not needed. That fixed it for us :)

**Comment by baltuonis** [comment]
I'm having the same issue.

Tried various package versions. None worked.
Tried removing Newtonsoft.Json - no luck.

		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
		
Here is the list of packages that we're using

		<PackageReference Include="Autofac" Version="6.3.0" />
		<PackageReference Include="Autofac.Extras.AggregateService" Version="6.1.1" />
		<PackageReference Include="Autofac.Extras.DynamicProxy" Version="6.0.0" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.0.0" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="7.2.0" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection.AzureFunctions" Version="6.0.0.81" />
		<PackageReference Include="Castle.Core.AsyncInterceptor" Version="1.7.0" />
		<PackageReference Include="CompareNETObjects" Version="4.67.0" />
		<PackageReference Include="CsvHelper" Version="27.1.1" />
		<PackageReference Include="EventFlow.Autofac" Version="0.81.4483" />
		<PackageReference Include="FluentValidation" Version="8.6.3" />
		<PackageReference Include="Microsoft.ApplicationInsights" Version="2.16.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="3.1.10" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.10" />
		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
		<PackageReference Include="System.ComponentModel.TypeConverter" Version="4.3.0" /

Error

```
Method 'Build' in type 'abc.CommandProcessor.Quotes.Function.OpenAPI.OpenApiExamples.QuoteIdExample' from assembly 'abc.CommandProcessor.Quotes.Function, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

   at System.Reflection.CustomAttribute._GetPropertyOrFieldData(RuntimeModule pModule, Byte** ppBlobStart, Byte* pBlobEnd, String& name, Boolean& bIsProperty, RuntimeType& type, Object& value)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.DocumentHelperExtensions.GetOpenApiParameters(IDocumentHelper helper, MethodInfo element, HttpTriggerAttribute trigger, NamingStrategy namingStrategy, VisitorCollection collection)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Build(Assembly assembly, OpenApiVersionType version)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerDocument(HttpRequest req, String extension, ExecutionContext ctx, ILogger log)
```
