### ISSUE TITLE
Swagger UI is not rendering when function app is deployed to Azure

### ISSUE THREAD

**Issue by rfigueroa2014** [Azure/azure-functions-openapi-extension#146]
Swagger UI is not rendering when function app is deployed to Azure

Get the following error:
Exception has been thrown by the target of an invocation.

**Comment by justinyoo** [comment]
@rfigueroa2014 Thanks for the issue. However, given the information is limited, we can't provide a solution for you.

**Comment by rfigueroa2014** [comment]
Basically when running locally, 
I can see all the functions (mine and Swagger)
![image](https://user-images.githubusercontent.com/8118552/122769659-bfbef680-d272-11eb-8f43-e9377eb4865e.png)

And if I got to the swaggerUI, the page renders
![image](https://user-images.githubusercontent.com/8118552/122769788-dfeeb580-d272-11eb-9ce8-f1e98cb1edfc.png)

But once I deploy to Azure
I only see my functions in Azure Function Apps and swaggerUi URl gets an "Exception has been thrown by the target of an invocation."
![image](https://user-images.githubusercontent.com/8118552/122770155-2a703200-d273-11eb-8bdd-c130ebca0975.png)



![image](https://user-images.githubusercontent.com/8118552/122769391-84bcc300-d272-11eb-9ab5-478248c7138a.png)

**Comment by rfigueroa2014** [comment]
2021-06-21T19:03:35Z   [Verbose]   Request successfully matched the route with name 'RenderSwaggerUI' and template 'api/swagger/ui'
2021-06-21T19:03:35Z   [Information]   Executing 'Functions.RenderSwaggerUI' (Reason='This function was programmatically called via the host APIs.', Id=550f6d3b-52a1-4a25-adda-8b45438b1aa0)
2021-06-21T19:03:35Z   [Information]   SwaggerUI page was requested.
2021-06-21T19:03:35Z   [Error]   Exception has been thrown by the target of an invocation.
2021-06-21T19:03:35Z   [Information]   Executed 'Functions.RenderSwaggerUI' (Succeeded, Id=550f6d3b-52a1-4a25-adda-8b45438b1aa0, Duration=45ms)

**Comment by justinyoo** [comment]
All endpoints starting with `Render*` are hidden by design.

> 2021-06-21T19:03:35Z [Verbose] Request successfully matched the route with name 'RenderSwaggerUI' and template 'api/swagger/ui'
> 2021-06-21T19:03:35Z [Information] Executing 'Functions.RenderSwaggerUI' (Reason='This function was programmatically called via the host APIs.', Id=550f6d3b-52a1-4a25-adda-8b45438b1aa0)
> 2021-06-21T19:03:35Z [Information] SwaggerUI page was requested.
> 2021-06-21T19:03:35Z [Error] Exception has been thrown by the target of an invocation.
> 2021-06-21T19:03:35Z [Information] Executed 'Functions.RenderSwaggerUI' (Succeeded, Id=550f6d3b-52a1-4a25-adda-8b45438b1aa0, Duration=45ms)

As your error message doesn't have enough information, you can manually set the environment variable on Azure:

```
AZURE_FUNCTIONS_ENVIRONMENT = "Development"
```

Then you'll be able to see the detailed error message and stack trace. Can you please try this?

**Comment by sizzler-5g** [comment]
I'm having a very similar issue, but can't find any hint to solve it in this post. 

On my side after enabling the environment as Development here is the  full error message:

> Object reference not set to an instance of an object.
>
 >  at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.<>c.<GetRuntimeFilenameAsync>b__42_1(KeyValuePair`2 target)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.<>c__DisplayClass42_0.<GetRuntimeFilenameAsync>b__3(<>f__AnonymousType0`3 r)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.GetRuntimeFilenameAsync(String functionAppDirectory)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.SetApplicationAssemblyAsync(String functionAppDirectory, Boolean appendBin)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.OpenApiHttpTriggerContextExtensions.AuthorizeAsync(Task`1 context, IHttpRequestDataObject req)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderOpenApiDocument(HttpRequest req, String version, String extension, ExecutionContext ctx, ILogger log)`
