### ISSUE TITLE
Could not load file or assembly 'Microsoft.Azure.WebJobs.Extensions.Http, Version=3.0.12.0

### ISSUE THREAD

**Issue by pmiller22** [Azure/azure-functions-openapi-extension#235]
I'm not sure how to proceed here. 
We're trying to use OpenAPI extension on an existing solution, but I get this error at runtime after adding the example that visual studio provides. 

```
Could not load file or assembly 'Microsoft.Azure.WebJobs.Extensions.Http, Version=3.0.12.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeParameterInfo parameter, RuntimeType caType)
   at System.Reflection.RuntimeParameterInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(ParameterInfo element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(ParameterInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](ParameterInfo element, Boolean inherit)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.ParameterInfoExtensions.ExistsCustomAttribute[T](ParameterInfo element, Boolean inherit)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.DocumentHelperExtensions.<>c.<GetHttpTriggerMethods>b__0_5(ParameterInfo q)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.DocumentHelperExtensions.<>c.<GetHttpTriggerMethods>b__0_4(MethodInfo p)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.DocumentHelperExtensions.GetHttpTriggerMethods(IDocumentHelper helper, Assembly assembly)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Build(Assembly assembly, OpenApiVersionType version)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderOpenApiDocument(HttpRequest req, String version, String extension, ExecutionContext ctx, ILogger log)
```

All traces of this package in my solution point to 3.0.12, so I'm at a loss for what's causing this

**Comment by pmiller22** [comment]
Sorry, this is a dup of https://github.com/Azure/azure-functions-openapi-extension/issues/183
