### ISSUE TITLE
CLI does not work due to assembly loading exception

### ISSUE THREAD

**Issue by basilfx** [Azure/azure-functions-openapi-extension#305]
**Describe the issue**

If the project uses different assembly versions, and the CLI tries to load the assembly with conflicting versions, it will not continue. The stack trace below shows this, but I have had similar problems due to conflicting `Newtonsoft.Json` versions.

My work-around is to create an additional CLI project that depends on the CLI project (from source) and the Swagger function app. I then start this utility that directly invokes the CLI's main method. The assemblies are then resolved correctly.

```
Could not load file or assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.DocumentHelperExtensions.<>c.<GetHttpTriggerMethods>b__0_4(MethodInfo p) in azure-functions-openapi-extension/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/DocumentHelperExtensions.cs:line 36
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.DocumentHelperExtensions.GetHttpTriggerMethods(IDocumentHelper helper, Assembly assembly, IEnumerable`1 tags) in azure-functions-openapi-extension/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/DocumentHelperExtensions.cs:line 31
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Build(Assembly assembly, OpenApiVersionType version) in azure-functions-openapi-extension/src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Document.cs:line 138
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Build(String assemblyPath, OpenApiVersionType version) in azure-functions-openapi-extension/src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Document.cs:line 124
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Program.Generate(String project, String configuration, String target, OpenApiVersionType version, OpenApiFormatType format, String output, Boolean console) in azure-functions-openapi-extension/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/Program.cs:line 90
```

**To Reproduce**
1. Have a working project (i.e. the web interface works)
2. Apply some workaround for #303
3. Run the CLI (e.g. `-p ../My.Project -v v3 -f yaml -t netcoreapp3.1 --console`
4. Observe it fails

**Expected behavior**
It generates a Swagger specification.

**Screenshots**
N/a

**Environment (please complete the following information, if applicable):**
- OS: macOS 12.0.1
- .NET SDK 5.0.402
- 0.9.0-preview (from source)

**Additional context**
N/a

**Comment by justinyoo** [comment]
As the PR, #489, has been merged, you can generate the OpenAPI doc on-the-fly, within the GitHub Actions workflow.
