### ISSUE TITLE
BUG: Object reference not set.... .net 6 functions

### ISSUE THREAD

**Issue by svrooij** [Azure/azure-functions-openapi-extension#352]
**Describe the issue**
When using this library in a new Azure Functions project (.net6, runtime V4) it works locally but not on Azure.

`Object reference not set to an instance of an object.`

**To Reproduce**
1. Create new Azure functions project with .Net 6
2. Deploy to Azure
3. Call `/api/swagger.json`

**Expected behavior**
I expect that swagger would just work like it does locally.

**Screenshots**

![image](https://user-images.githubusercontent.com/1292510/152005361-87741b39-4d27-450d-a6b7-0bb5db80fbb5.png)

**Environment (please complete the following information, if applicable):**
 - OS: Azure (Windows Service plan, `FUNCTIONS_EXTENSION_VERSION` = `~4`, `FUNCTIONS_WORKER_RUNTIME` = `dotnet`)
 - Version `1.0.0` (nuget)

**Comment by vinhent** [comment]
I am having the exact same issue.

**Comment by PedroLucasSilva** [comment]
I had the same problem and I solved it based on an old issue. Where the person indicated that all projects on their system must have at least one dependency. I added a random package to a project of mine that didn't have any and it started working.

**Comment by McNerdius** [comment]
Bizarre issue.  The "at least one dependency per project" workaround worked for me as well.

**Comment by vinhent** [comment]
If fixed it for me as well. I had a project that contains only interfaces and didn't have any dependencies.

I added this randomly:

![image](https://user-images.githubusercontent.com/10554329/153229475-4819b074-4a36-4577-86f6-c2e1a1abeb89.png)

Do you have an idea of a better nuget package to be used for that workaround?

**Comment by justinyoo** [comment]
@svrooij It's a known issue #302

**Comment by svrooij** [comment]
@justinyoo But why does it work locally?

**Comment by justinyoo** [comment]
@svrooij I have no idea. I haven't got such an experience at all. I use exactly the same settings (.NET 6, v4, in-proc). Would you please tell me how to reproduce the issue?

**Comment by svrooij** [comment]
Since the comments above provided a work-around, this is what triggers the error:

1. Create a new azure Functions app with OpenApi support
2. Add an additional project, WITHOUT dependencies.
3. Add the second project as a project dependency to the functions project.
4. The swagger ui should still appear locally, and the endpoint from the template should be in the swagger ui.
5. Publish to Azure and it stops working, with the error above in the ligging.

**Comment by justinyoo** [comment]
@svrooij Alright. I tried to reproduce on my end, but... my app is still working. Here's my app structure:

https://github.com/fitability/fitability-api/tree/main/users

* Api.Users ➡️ main function app - .NET 6, in-proc, v4
* Api.Models ➡️ class library with no dependency, but added to Api.Users - .NET Standard 2.0
* Api.Users.Models ➡️ class library with no dependency, no added to Api.Users - .NET Standard 2.0

They are buit and deployed to Azure through GitHub Actions, and it's working.

**Comment by chris-parker-bliss** [comment]
I wanted to make a quick note to say that we've just run into this issue when running locally - in our setup we've got an Azure function project referencing a "shared" `net6.0` class library.

Using the hack suggested by @svrooij - adding the `Microsoft.Extensions.DependencyInjection.Abstractions` dependency to that shared project - has gotten it working again.

**Comment by jassent** [comment]
I upgraded from .81 preview which was running fine. This is .net6 running isolated/out-of-process.  

When using the 1.1.0 package, I can use the Swagger UI and generate the OpenApi document.

However, upgrading to 1.2.0 causes the OpenApi endpoint (/api/openapi/v2.json) to return the error listed below. The Swagger UI and Swagger.json endpoint (/api/swagger.json) work find under 1.2.0.  

This is not an issue of needing to include a dependency as my project has many dependencies in all shared solutions. 

Also, for some reason both 1.1.0 and 1.20.0 required adding System.Drawing.Common which seems like an odd package to require.

`Object reference not set to an instance of an object.

   at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Extensions.DocumentHelperExtensions.<>c__DisplayClass6_0.<GetOpenApiParameters>b__5(KeyValuePair`2 p)
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Extensions.DocumentHelperExtensions.GetOpenApiParameters(IDocumentHelper helper, MethodInfo element, HttpTriggerAttribute trigger, NamingStrategy namingStrategy, VisitorCollection collection, OpenApiVersionType version)
   at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Document.Build(Assembly assembly, OpenApiVersionType version)
   at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Functions.OpenApiTriggerFunction.RenderOpenApiDocument(HttpRequestData req, String version, String extension, FunctionContext ctx)`

**Comment by svrooij** [comment]
@justinyoo it happens when there are no dependencies in the class library and it is set to `.NET6` as target framework.

![image](https://user-images.githubusercontent.com/1292510/160783301-ea8dadc4-7d20-453c-be4c-e1f715effb55.png)

**Comment by chris-parker-bliss** [comment]
Hi @justinyoo - I can confirm that even after updating to v1.3.0 of the `Microsoft.Azure.WebJobs.Extensions.OpenApi` package I'm still seeing the following error when my function app references a `net6.0` class library which has no dependencies:

```
Object reference not set to an instance of an object.

   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.<>c.<GetRuntimeFilenameAsync>b__43_1(KeyValuePair`2 target)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.<>c__DisplayClass43_0.<GetRuntimeFilenameAsync>b__3(<>f__AnonymousType0`3 r)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.GetRuntimeFilenameAsync(String functionAppDirectory)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.SetApplicationAssemblyAsync(String functionAppDirectory, Boolean appendBin)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.OpenApiHttpTriggerContextExtensions.AuthorizeAsync(Task`1 context, IHttpRequestDataObject req)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerUI(HttpRequest req, ExecutionContext ctx, ILogger log)
```
