### ISSUE TITLE
Swagger UI is not rendering Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http'

### ISSUE THREAD

**Issue by DureSameen** [Azure/azure-functions-openapi-extension#355]
I have added open api support in my function app(.net 6 Isolated) . But when I try to load swagger UI via http://localhost:7071/api/swagger/ui . it gives me an exception.

Steps

1. add in program file
             

>   .ConfigureFunctionsWorkerDefaults(worker => { 
>                    worker.UseNewtonsoftJson();
>                    
>                 })
>                 .ConfigureOpenApi()

2. added package
   

>  Microsoft.Azure.Functions.Worker.Extensions;

 3. Added open API attribute on all HTTP trigger functions
       

>  [Function("CreateObject")]
>         [OpenApiOperation(operationId: "CreateObject", tags: new[] { "type-less" ,"objects", "pub/sub"})]
> 

 
 
 
 Executing 'Functions.RenderSwaggerUI' (Reason='This function was programmatically called via the host APIs.', Id=02e81a47-4fdd-437d-8cdb-d015476fd010)
[2022-02-06T06:37:20.007Z] [06:37:20 INF] SwaggerUI page was requested.
[2022-02-06T06:37:20.342Z] Executed 'Functions.RenderSwaggerUI' (Failed, Id=02e81a47-4fdd-437d-8cdb-d015476fd010, Duration=734ms)
[2022-02-06T06:37:20.344Z] System.Private.CoreLib: Exception while executing function: Functions.RenderSwaggerUI. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.)
[2022-02-06T06:37:20.347Z]  ---> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
[2022-02-06T06:37:20.350Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Extensions.OpenApiHttpRequestDataExtensions.Queries(HttpRequestData req)
[2022-02-06T06:37:20.354Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.HttpRequestObject..ctor(HttpRequestData req)
[2022-02-06T06:37:20.357Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Functions.OpenApiTriggerFunction.RenderSwaggerUI(HttpRequestData req, FunctionContext ctx)
[2022-02-06T06:37:20.360Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.DefaultOpenApiHttpTrigger.RenderSwaggerUI(HttpRequestData req, FunctionContext ctx)
[2022-02-06T06:37:20.362Z]    --- End of inner exception stack trace ---
[2022-02-06T06:37:20.364Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2022-02-06T06:37:20.366Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2022-02-06T06:37:20.369Z]    at System.Threading.Tasks.Task`1.get_Result()
[2022-02-06T06:37:20.371Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2022-02-06T06:37:20.374Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2022-02-06T06:37:20.377Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
[2022-02-06T06:37:20.379Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2022-02-06T06:37:20.382Z] --- End of stack trace from previous location ---
[2022-02-06T06:37:20.388Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2022-02-06T06:37:20.404Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2022-02-06T06:37:20.408Z] --- End of stack trace from previous location ---
[2022-02-06T06:37:20.412Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2022-02-06T06:37:20.419Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13

**Comment by SilverioMiranda** [comment]
Related to #296 
https://github.com/Azure/azure-functions-openapi-extension/pull/318

**Comment by Code-Ninja-2k** [comment]
Hi, I am getting the same issue on dotnet 7 isolated AF v4

Executed 'Functions.RenderSwaggerUI' (Failed, Id=7ed1a6bf-4909-4535-a229-595cafe4f27b, Duration=243ms)
[2023-01-23T11:11:23.647Z] System.Private.CoreLib: Exception while executing function: Functions.RenderSwaggerUI. System.Private.CoreLib: Result: Failure
[2023-01-23T11:11:23.647Z] Exception: System.AggregateException: One or more errors occurred. (Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.)
[2023-01-23T11:11:23.647Z]  ---> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by ElliotWood** [comment]
> Hi, I am getting the same issue on dotnet 7 isolated AF v4
> 
> Executed 'Functions.RenderSwaggerUI' (Failed, Id=7ed1a6bf-4909-4535-a229-595cafe4f27b, Duration=243ms) [2023-01-23T11:11:23.647Z] System.Private.CoreLib: Exception while executing function: Functions.RenderSwaggerUI. System.Private.CoreLib: Result: Failure [2023-01-23T11:11:23.647Z] Exception: System.AggregateException: One or more errors occurred. (Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.) [2023-01-23T11:11:23.647Z] ---> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Same here exactly.

**Comment by justinyoo** [comment]
Yeah, it was fixed in v1.2.0 - v1.4.0. It broke again on v1.5.0. It will be fixed on v.1.5.1
