### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Balaji-kn** [Azure/azure-functions-openapi-extension#378]
**Describe the issue**
OpenApiRequestBody not able to serialise the JsonObject datatype (System.Text.Json.Nodes) in version 1.2.0 .

**To Reproduce**
1. Create new Azure Function POST API
2. Add OpenApiRequestBody attribute with customModel
3. In Model, use JsonObject for one the parameter.
4. Run the application
5. See error

**Expected behavior**
OpenApiRequestBody should able to serialise the JsonObject data type and should able to generate the swagger.json file and swagger UI.

**Screenshots**
<img width="724" alt="image" src="https://user-images.githubusercontent.com/100765549/156339912-f150fbe1-4db8-4a18-b1d7-b59ae3a473de.png">

Index was outside the bounds of the array.

   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.TypeExtensions.GetUnderlyingType(Type type)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Visitors.ListObjectTypeVisitor.Visit(IAcceptor acceptor, KeyValuePair`2 type, NamingStrategy namingStrategy, Attribute[] attributes)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Visitors.OpenApiSchemaAcceptor.Accept(VisitorCollection collection, NamingStrategy namingStrategy)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Visitors.ObjectTypeVisitor.ProcessProperties(IOpenApiSchemaAcceptor instance, String schemaName, Dictionary`2 properties, NamingStrategy namingStrategy)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Visitors.ObjectTypeVisitor.Visit(IAcceptor acceptor, KeyValuePair`2 type, NamingStrategy namingStrategy, Attribute[] attributes)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Visitors.OpenApiSchemaAcceptor.Accept(VisitorCollection collection, NamingStrategy namingStrategy)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.DocumentHelper.GetOpenApiSchemas(List`1 elements, NamingStrategy namingStrategy, VisitorCollection collection)
   at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Document.Build(Assembly assembly, OpenApiVersionType version)
   at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Functions.OpenApiTriggerFunction.RenderSwaggerDocument(HttpRequestData req, String extension, FunctionContext ctx)

**Environment (please complete the following information, if applicable):**
 - OS: [Mac]
 - Browser [chrome]
 - Version [1.2.0, 1.1.0]

**Comment by justinyoo** [comment]
@Balaji-kn Thanks for the issue! `System.Text.Json` isn't supported yet.

**Comment by justinyoo** [comment]
#154

**Comment by mujtabashareef** [comment]
Is there a workaround if I am still using System.Text.Json? I want to be able to display a custom example for a property of type `JsonObject`.

**Comment by pondchamp** [comment]
> Is there a workaround if I am still using System.Text.Json? I want to be able to display a custom example for a property of type `JsonObject`.

I was able to work around this issue by replacing OpenApi references to `JsonObject` with `Dictionary<string, object>` since those are interchangeable in my case

**Comment by robertjf** [comment]
I am seeing this issue on .net8 in an Isolated mode FunctionApp with the following:

```csharp
[OpenApiRequestBody(contentType: "application/json", bodyType: typeof(EvidenceUpload), Required = true, Description = "Describes the evidence to be uploaded")]
```

Model:
```csharp
public class EvidenceUpload
{
    public int ActivityId { get; set; }
    public required string EvidenceName { get; set; }
    public required IFormFile File { get; set; }
}
```

Removing `public required IFormFile File { get; set; }` from the above object works, but with it we get the "Index was outside the bounds of the array." error.

**Comment by logeshpalani33** [comment]
@robertjf  If we convert IFormFile to byte[] , it started working, i'm trying to figure out, how we can use IFormFile @justinyoo is IFormFile, is not supported yet?
