### ISSUE TITLE
"Index was outside the bounds of the array" OpenApiResponseWithBody List

### ISSUE THREAD

**Issue by vrooijen** [Azure/azure-functions-openapi-extension#380]
Microsoft.Azure.Webjobs.Extensions.OpenApi 1.2.0
.NET Core 3.1

I tried
```c#
[OpenApiResponseWithBody(HttpStatusCode.BadRequest, MediaTypeNames.Application.Json, typeof(ValidationResponse))]
```
but got
```
Index was outside the bounds of the array.

   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.TypeExtensions.GetOpenApiSubTypeName(Type type, NamingStrategy namingStrategy)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.TypeExtensions.GetOpenApiDescription(Type type)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.OpenApiResponseWithBodyAttributeExtensions.ToOpenApiResponse(OpenApiResponseWithBodyAttribute attribute, NamingStrategy namingStrategy, VisitorCollection collection, OpenApiVersionType version)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.DocumentHelper.<>c__DisplayClass7_0.<GetOpenApiResponses>b__1(OpenApiResponseWithBodyAttribute p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.DocumentHelper.GetOpenApiResponses(MethodInfo element, NamingStrategy namingStrategy, VisitorCollection collection, OpenApiVersionType version)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Build(Assembly assembly, OpenApiVersionType version)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerDocument(HttpRequest req, String extension, ExecutionContext ctx, ILogger log)
```

The response type can be as easy as the following, as long as it is a collection.
```c#
public class ValidationResponse : List<string>
{
}
```

When specifying directly it works, however I want to type it.

```c#
[OpenApiResponseWithBody(HttpStatusCode.BadRequest, MediaTypeNames.Application.Json, typeof(List<string>))]
```

**Comment by vrooijen** [comment]
> [vrooijen](https://github.com/vrooijen) did you find a solution to this? I am facing the same error.

Yes, specify the type directly, as described on the last line. However this is not a solution for my question, more a kind of workaround

**Comment by briandunnington** [comment]
Appears to be the similar to #313  - I think the root cause is here: https://github.com/Azure/azure-functions-openapi-extension/blob/a1661dbec6c2e215c9f3bb3e9d0e2749ae731520/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/TypeExtensions.cs#L579 (at least for the Dictionary case - likely a few lines down for the List case). In both cases, it assumes an array index that appears to be wrong.

**Comment by archubbuck** [comment]
I'm running into this same issue with `Microsoft.Graph.User`

**Comment by Qualizorg** [comment]
Agree, would be nice to have a solid solution.

**Comment by AJMauger** [comment]
Here is a working example https://github.com/AJMauger/sunstealer.azure.functions.

Note Model1.cs this defines an Example Model, note OpenApiCustomUIOptions.cs this maps example to open API 3 doc schema.  Note Function1.cs this binds the Example to the API.

**Comment by Shuvajyoti** [comment]
Facing similar exception while using System.Text.Json as the serialization/deserialization library. Is there any solution for this yet.

**Comment by pondchamp** [comment]
This issue appears to be related: https://github.com/Azure/azure-functions-openapi-extension/issues/588
