### ISSUE TITLE
Nullable<byte> => "Sequence contains no elements"

### ISSUE THREAD

**Issue by tommck** [Azure/azure-functions-openapi-extension#396]
**Describe the issue**
I'm getting an exception trying to render the Swagger Document when my API includes a class that has a Nullable<byte> in it.

**To Reproduce**
1. Use Visual Studio to create a new Azure Functions app with Open API Support
2. Add a "Dto" class with one property: `public Nullable<byte> Byte { get; set; }`
3. Set the `OpenApiResponseWithBody` `bodyType` to be `typeof(Dto)`
4. Run the app
5. try to run the Swagger UI or download the JSON file
6. See the error

**Expected behavior**
I expect it not to throw an error

**Error Output**

```
Sequence contains no elements

   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Visitors.NullableObjectTypeVisitor.Visit(IAcceptor acceptor, KeyValuePair`2 type, NamingStrategy namingStrategy, Attribute[] attributes)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Visitors.OpenApiSchemaAcceptor.Accept(VisitorCollection collection, NamingStrategy namingStrategy)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Visitors.ObjectTypeVisitor.ProcessProperties(IOpenApiSchemaAcceptor instance, String schemaName, Dictionary`2 properties, NamingStrategy namingStrategy)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Visitors.ObjectTypeVisitor.Visit(IAcceptor acceptor, KeyValuePair`2 type, NamingStrategy namingStrategy, Attribute[] attributes)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Visitors.OpenApiSchemaAcceptor.Accept(VisitorCollection collection, NamingStrategy namingStrategy)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.DocumentHelper.GetOpenApiSchemas(List`1 elements, NamingStrategy namingStrategy, VisitorCollection collection)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Build(Assembly assembly, OpenApiVersionType version)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerDocument(HttpRequest req, String extension, ExecutionContext ctx, ILogger log)
```

**Environment (please complete the following information, if applicable):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 99

**Additional context**
Demo Project attached
[DeleteMe.zip](https://github.com/Azure/azure-functions-openapi-extension/files/8324203/DeleteMe.zip)

**Comment by sumangeorge** [comment]
facing the same issue

**Comment by ashirafumiiro** [comment]
I got the same issue with `char?`

**Comment by justinyoo** [comment]
It's now fixed. Please stay tuned on the next release. Closing this issue.
