### ISSUE TITLE
OpenApiRequestBody An item with the same key has already been added

### ISSUE THREAD

**Issue by dannythomas13** [Azure/azure-functions-openapi-extension#433]
I have created a new Azure Function in VS2022 targetting .net 6 isolated and am now getting the following error:
An item with the same key has already been added. Key: 'name of my parameter class'

The same code worked for a .net 6 Azure Function that was not running as an isolated process

**Comment by beukerz** [comment]
I have the same problem. It works find if you use a primitive type ie string. However if you use your own custom object it returns the error:

An item with the same key has already been added. Key: 'name of my parameter class'.

For example this works fine:
[OpenApiRequestBody(contentType: "application/json", bodyType: typeof(string), Description = "Parameters", Required = true)]

And this returns an error:
[OpenApiRequestBody(contentType: "application/json", bodyType: typeof(TestModel), Description = "Parameters", Required = true)]

The same issue exists for the OpenApiResponseWithBody. Please let us know what we can do to fix this.

**Comment by taipignas** [comment]
Same happens with the response attribute. I downgraded to Microsoft.Azure.Functions.Worker.Extensions.OpenApi 1.2.0 and the issue is gone.

An item with the same key has already been added. Key: mockSearchRequestDTO

   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.DocumentHelper.GetOpenApiSchemas(List`1 elements, NamingStrategy namingStrategy, VisitorCollection collection)
   at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Document.Build(Assembly assembly, OpenApiVersionType version)
   at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Functions.OpenApiTriggerFunction.RenderSwaggerDocument(HttpRequestData req, String extension, FunctionContext ctx)

**Comment by klemmchr** [comment]
I'm having this issue using the response attribute together with a generic response type. As soon as I have two attributes with a different generic type I get this error:

`An item with the same key has already been added. Key: apiResponse_iEnumerable1`

**Comment by CedNZ** [comment]
I have this same issue, downgrading to 1.2.0 (or building the latest source and using that) works for me

**Comment by CyberMutter** [comment]
Having the same issue after upgrading to version 1.3.0, downgrading to 1.2.0 works also for me.

**Comment by diogokunde** [comment]
Same issue here. Downgrade to 1.2.0 did not resolve too.

**Comment by msundquist-onebridge** [comment]
I'm also having this issue. Downgrading to 1.2.0 _did_ fix the issue for me as well.

**Comment by BronwenZ** [comment]
Same issue here. Can't downgrade to 1.2.0  due to (https://github.com/Azure/azure-functions-openapi-extension/issues/387)

**Comment by jeckyl2010** [comment]
> @justinyoo
> 
> There are a lot of duplicates regarding this issue now. I see that one duplicate has been closed with two linked PRs suggesting a fix has been made. (#407)
> 
> Due to this other bug (#387) I am unable to downgrade while we wait for the fix to be released.
> 
> This is becoming pretty urgent for us. Is it possible to get a patch with the fix?

Same issues here - basically prevent us from automatically generating OpenAPI specs, which we use for autogenerating frontend TypeScript data contracts. 

Is anyone aware of any alternative solutions, that work with Azure Functions v4, dotnet-isolated process and .NET 6.

Any ETA on when this will be fixed!!

**Comment by maurert** [comment]
I have the same issue in 1.3.0. (1.2.0 works fine.)

**Comment by jeckyl2010** [comment]
I'm wondering if the package development is stalled and if someone else have some better alternative packages to generate OpenAPI documentation for .NET 6 Azure Function projects using dot-isolated coding scheme.

**Comment by brennfoster** [comment]
I just discovered that if I move the custom object into a separate project then the open api extension renders the swagger document successfully.

Sharing for anyone still struggling with this and needing a work around.

**Comment by Dongbumlee** [comment]
> 

I regret I found your thread so lately. I had to spend a whole day to find work around. 
I confirmed it works! Really appreciate it. 👍🏻
