### ISSUE TITLE
OpenApiResponseWithBody containing property named `parameters` throws exception

### ISSUE THREAD

**Issue by KeenFann** [Azure/azure-functions-openapi-extension#474]
**Describe the issue**
Using a class that contains a property named `parameters` in the `OpenApiResponseWithBody` attribute crashes the `../swagger.json` endpoint.

Using version `1.3.0`.

**To Reproduce**
Decorate a function with this:
```c#
[OpenApiOperation]
[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(Output))]
```

The class `Output` looks like this
```c#
public class Output
{
    public string parameters { get; set; }
}
```

Returns this when calling `/swagger.json` endpoint:
```
Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.

   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](IEnumerable`1 source)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.Render(OpenApiSpecVersion version, OpenApiFormat format)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.<>c__DisplayClass18_0.<RenderAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Document.RenderAsync(OpenApiSpecVersion version, OpenApiFormat format)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerDocument(HttpRequest req, String extension, ExecutionContext ctx, ILogger log)
```

**Comment by justinyoo** [comment]
@KeenFann Thanks for the issue! If you change the property name to something else, say `MyParameter` and give it a decorator of `[JsonProperty("parameter")]`, does that still throw an exception?

**Comment by KeenFann** [comment]
Yes, using `[JsonProperty("parameters")]` with a different property name still throws the exception.

**Comment by singingknight** [comment]
Got the same issue using version 1.5.0.

Downgrading to version 1.1.0 solved the issue which seems to have been introduced in 1.2.0

**Comment by jcezardasilva** [comment]
I have a similar issue.
I'm trying to use a multipart/form-data with:

`[OpenApiRequestBody(contentType: "multipart/form-data", bodyType: typeof(MultiPartFormData))]`

the MultiPartFormData is like:

`    public class MultiPartFormData
    {
        public byte[] File { get; set; }
    }`


Using [Microsoft.Azure.WebJobs.Extensions.OpenApi] version 1.1.0 and .Net6 the parameter is not shown in the swagger.
Upgrading [Microsoft.Azure.WebJobs.Extensions.OpenApi] to 1.2.0 or earlier then throw the exception:

`Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.`

**Comment by planUnd** [comment]
Same Issue on 1.5.1 downgrading to 1.1.0 solved the problem

**Comment by camartinezal** [comment]
Hello,

I'm having the same issue, but using .NET 8 in-process. I can't change the property name. I tried downgrading to 1.1.0, but in this case OpenApi is not finding the operations.

**Comment by patrikrosquist67** [comment]
I had the same issue. .Net8, in-process, version 1.5.1. Could not downgrade since other stuff used are bound to that version.
My only solution was to create a copy of the violating object with the same schema and "parameters" renamed to "params".
Then I used that copy as spec in OpenApiRequestBody declaration and in the endpoint method I just mapped the copy to the original object. Not nice but...

**Comment by martynnorman** [comment]
still an issue in version 1.6.0 - .net 8 isolated
